name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      prs_created: ${{ steps.release.outputs.prs_created }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4

  rebuild-plugins:
    needs: release-please
    if: needs.release-please.outputs.prs_created == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Parse PR information
        id: pr-info
        uses: actions/github-script@v8
        env:
          PR_JSON: ${{ needs.release-please.outputs.pr }}
        with:
          script: |
            const pr = JSON.parse(process.env.PR_JSON);
            core.setOutput('branch', pr.headBranchName);
            core.info(`Release PR branch: ${pr.headBranchName}`);

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr-info.outputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build plugins
        run: pnpm build

      - name: Commit rebuilt dist files
        uses: actions/github-script@v8
        with:
          script: |
            const commit = require('./scripts/commit.js');
            await commit({github, context, core, glob, exec});
